Tox: `pep8` on Python 3.9 fails: AttributeError
If a machine has Python 3.9 as the default `python3`, tox -e venv fails
with:

    AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

This is due to `pyflakes` being limited to version 1.2.3 by installing
`hacking==1.1.0`.

So we force the tox `pep8` enviroment to Python 3.6, like the `pylint`
enviroment.